#!/usr/bin/env python3
"""update_ercot_glossary.py — build/refresh the ERCOT glossary reference doc.

Source: https://www.ercot.com/glossary

The public glossary page is JavaScript-rendered: the A-Z letter links just filter
a single array that is embedded inline in the page as `glossaryData = [ {term_s,
definition_html_raw}, ... ]`. So instead of crawling per-letter pages (which don't
exist as separate URLs), this fetches the one page, extracts that array, converts
each definition's HTML to clean text, and writes a living glossary document.

Outputs (per Power.Talks conventions, reference material -> Database Codes/reference_info):
  Database Codes/reference_info/ERCOT_Glossary.md     ← human-readable, A-Z grouped
  Database Codes/reference_info/ercot_glossary.json   ← machine-readable companion

Idempotent: both files are overwritten each run. When the JSON already exists, a
short change summary (added / removed / changed terms) is printed.

Usage:
  py -3 "Database Codes/reference_info/update_ercot_glossary.py"
  py -3 "Database Codes/reference_info/update_ercot_glossary.py" --quiet
"""

import argparse
import html
import json
import os
import re
import sys
from datetime import datetime

import requests

HERE = os.path.dirname(os.path.abspath(__file__))
GLOSSARY_URL = "https://www.ercot.com/glossary"
MD_PATH = os.path.join(HERE, "ERCOT_Glossary.md")
JSON_PATH = os.path.join(HERE, "ercot_glossary.json")
UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Power.Talks glossary refresh"


def fetch_page(url, retries=4):
    last = None
    for attempt in range(1, retries + 1):
        try:
            r = requests.get(url, headers={"User-Agent": UA}, timeout=60)
            if r.status_code == 200 and r.text:
                return r.text
            last = f"HTTP {r.status_code}"
        except requests.RequestException as e:  # noqa: PERF203
            last = str(e)
    sys.exit(f"ERROR: could not fetch {url} ({last})")


def extract_glossary(html_text):
    """Pull the embedded `glossaryData = [...]` array out of the page and return
    it as a list of {term_s, definition_html_raw} dicts."""
    i = html_text.find("glossaryData")
    if i == -1:
        _dump_debug(html_text)
        sys.exit("ERROR: 'glossaryData' not found — page structure changed. "
                 "Raw page dumped to _glossary_raw.html for inspection.")
    start = html_text.find("[", i)
    try:
        data, _end = json.JSONDecoder().raw_decode(html_text[start:])
    except json.JSONDecodeError as e:
        _dump_debug(html_text)
        sys.exit(f"ERROR: could not parse glossaryData JSON ({e}). "
                 "Raw page dumped to _glossary_raw.html.")
    return [d for d in data if d.get("term_s")]


def _dump_debug(html_text):
    with open(os.path.join(HERE, "_glossary_raw.html"), "w", encoding="utf-8") as f:
        f.write(html_text)


def html_to_text(raw):
    """Convert a definition's HTML fragment to clean, multi-line plain text."""
    h = raw or ""
    h = re.sub(r"(?i)<\s*br\s*/?>", "\n", h)
    h = re.sub(r"(?i)<\s*li[^>]*>", "\n- ", h)
    h = re.sub(r"(?i)</\s*(p|div|li|tr|h[1-6])\s*>", "\n", h)
    h = re.sub(r"(?i)<\s*(p|ul|ol|div|table|tbody|tr|td|h[1-6])[^>]*>", "", h)
    h = re.sub(r"<[^>]+>", "", h)              # strip any remaining tags
    h = html.unescape(h)
    lines = [ln.strip() for ln in h.splitlines()]
    return "\n".join(ln for ln in lines if ln)


def _group_key(term):
    c = term.strip()[:1].upper()
    return c if c.isalpha() else "#"


def build_markdown(entries):
    terms = sorted(entries, key=lambda d: d["term_s"].lower())
    groups = {}
    for d in terms:
        groups.setdefault(_group_key(d["term_s"]), []).append(d)

    now = datetime.now().strftime("%Y-%m-%d")
    out = [
        "# ERCOT Glossary",
        "",
        "> Power system, grid, and market-operations terminology used by ERCOT.",
        "",
        f"- **Source:** <{GLOSSARY_URL}>",
        f"- **Terms:** {len(terms)}",
        f"- **Last updated:** {now}",
        "",
        "_Auto-generated by `Database Codes/reference_info/update_ercot_glossary.py`._",
        "",
        "---",
        "",
    ]
    for letter in sorted(groups):
        out.append(f"## {letter}\n")
        for d in groups[letter]:
            text = html_to_text(d["definition_html_raw"])
            out.append(f"**{d['term_s']}**")
            out.append(text if text else "_(no definition provided)_")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def change_summary(new_entries):
    """Compare with the previously saved JSON; return a one-line summary string."""
    if not os.path.exists(JSON_PATH):
        return f"first build: {len(new_entries)} terms."
    try:
        old = {d["term_s"]: (d.get("definition_html_raw") or "")
               for d in json.load(open(JSON_PATH, encoding="utf-8")).get("terms", [])}
    except Exception:  # noqa: BLE001 — corrupt/old format => treat as first build
        return f"rebuild: {len(new_entries)} terms (previous file unreadable)."
    new = {d["term_s"]: (d.get("definition_html_raw") or "") for d in new_entries}
    added = sorted(set(new) - set(old))
    removed = sorted(set(old) - set(new))
    changed = sorted(t for t in set(new) & set(old) if new[t] != old[t])
    parts = [f"{len(new)} terms"]
    if added:
        parts.append(f"+{len(added)} added")
    if removed:
        parts.append(f"-{len(removed)} removed")
    if changed:
        parts.append(f"~{len(changed)} changed")
    if not (added or removed or changed):
        parts.append("no changes")
    return " | ".join(parts)


def main():
    ap = argparse.ArgumentParser(description="Refresh the ERCOT glossary reference doc.")
    ap.add_argument("--quiet", action="store_true", help="minimal output")
    args = ap.parse_args()

    page = fetch_page(GLOSSARY_URL)
    entries = extract_glossary(page)
    if not entries:
        sys.exit("ERROR: glossary array parsed but empty.")

    summary = change_summary(entries)

    os.makedirs(HERE, exist_ok=True)
    with open(MD_PATH, "w", encoding="utf-8") as f:
        f.write(build_markdown(entries))
    with open(JSON_PATH, "w", encoding="utf-8") as f:
        json.dump({"source": GLOSSARY_URL,
                   "retrieved_at": datetime.now().isoformat(timespec="seconds"),
                   "count": len(entries),
                   "terms": sorted(entries, key=lambda d: d["term_s"].lower())},
                  f, ensure_ascii=False, indent=2)

    print(f"ERCOT glossary: {summary}")
    if not args.quiet:
        print(f"Saved:\n  {MD_PATH}\n  {JSON_PATH}")


if __name__ == "__main__":
    main()
